
[font]
size = 12.0

[font.bold]
family = "CommitMonoNerdFont"

[font.italic]
family = "CommitMonoNerdFont"

[font.normal]
family = "CommitMonoNerdFont"

[window]
opacity = 1

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/onedark.toml"
]
